### ISSUE TITLE
想试试外网访问

### ISSUE THREAD

**Issue by iszcz** [q1006608006/windrop#19]
突发奇想试试外网能否互相传输，然后在第一步扫码绑定出错了.
扫码后填写了外网域名/ip和端口，弹出提示：核验失败，认证码过期或已被使用；并且在windows软件日志里也发现了同样记录

**Comment by q1006608006** [comment]
因为绑定时会验证IP地址，服务器收到的实际IP可能与你手动输入的IP地址不一致。

假如需要外网访问，可以通过主机所在局域网搭建代理，手机连接时，选择使用代理，代理地址输入局域网代理服务所在机器的IP（最好是局域网内），这个方案我已经验证可行。

后面是我的成功方案：我在我的电脑上（安装了windropserver的机器）同时安装了frpc应用，该应用连接到一个公网地址，我在连接时选择了使用代理，代理地址输入127.0.0.1（因为是在同一机器安装的，且我的frpc绑定的本地ip是127.0.0.1），即可成功连接且可以正常传递内容。

 @方案二：使用压缩软件打开windrop-${version}.jar，进入路径：BOOT-INF\classes，编辑application.yml，修改logging.level.valid的参数为debug，覆盖保存后，重启windrop，再次尝试连接，在日志中你就可以看到你的实际连接地址了（假如没有这个字段可能这个版本我还没发，诶嘿）

**Comment by q1006608006** [comment]
该操作是一个很危险的操作，现有功能可实现但不推荐也不建议不懂代码的用户操作
